name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container: "m00qek/snes-game-patcher:alpine"
    steps:
    - uses: actions/checkout@v2

    - name: Download external dependencies
      run: make prepare EXECUTE=''
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

    - name: Assemble game changes
      run: make rom EXECUTE=''

    - name: Create patch
      run: make patch EXECUTE=''

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/release/*.bps"
        token: ${{ secrets.GITHUB_TOKEN }}
